general.import = [
	"~/.config/alacritty/dracula.toml"
]

[font]
size = 15.0

[font.normal]
family = "Iosevka"
style = "Regular"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 2

